
BEGIN;

CREATE TABLE articles_citing (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    cited_article_id bigint REFERENCES articles(id),
    cited_user_id bigint REFERENCES users(id),
    div_tag text,
    is_processed BOOLEAN DEFAULT FALSE
);

ALTER TABLE articles ADD COLUMN "is_processed_2" boolean DEFAULT FALSE;
ALTER TABLE articles ADD COLUMN "is_found" boolean DEFAULT TRUE;

COMMIT;
