-- Active: 1706448604919@@127.0.0.1@5433@cities
BEGIN;

CREATE TABLE users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    orcid TEXT,
    name VARCHAR(255) NOT NULL,
    google_scholar_code TEXT,
    profile_url TEXT,
    is_found BOOLEAN DEFAULT FALSE,
    is_processed boolean DEFAULT FALSE
);

ALTER TABLE users ADD COLUMN "h_endeksi" INTEGER;
ALTER TABLE users ADD COLUMN "i10_endeksi" INTEGER;
ALTER TABLE users ADD COLUMN "h_endeksi_2019_sonrası" INTEGER;
ALTER TABLE users ADD COLUMN "i10_endeksi_2019_sonrası" INTEGER;
ALTER TABLE users ADD COLUMN "alinti_sayısı" INTEGER;
ALTER TABLE users ADD COLUMN "alinti_sayısı_2019_sonrası" INTEGER;

CREATE TABLE articles (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    user_id bigint REFERENCES users(id),
    tr_tag text,
    name text,
    makale_kod text,
    alinti_kod text,
    alinti_sayisi INTEGER,
    makale_url text,
    alinti_url text,
    is_processed BOOLEAN DEFAULT FALSE
);

CREATE TABLE articles2 (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    tr_tag text,
    name text,
    makale_kod text,
    alinti_kod text,
    alinti_sayisi INTEGER,
    makale_url text,
    alinti_url text,
    is_processed BOOLEAN DEFAULT FALSE,
    is_processed_2 boolean DEFAULT FALSE,
    is_found boolean DEFAULT TRUE
);


COMMIT;



BEGIN;

CREATE TABLE articles_citing (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    cited_article_id bigint REFERENCES articles(id),
    cited_user_id bigint REFERENCES users(id),
    div_tag text,
    is_processed BOOLEAN DEFAULT FALSE
);

ALTER TABLE articles ADD COLUMN "is_processed_2" boolean DEFAULT FALSE;
ALTER TABLE articles ADD COLUMN "is_found" boolean DEFAULT TRUE;

COMMIT;



CREATE TABLE user_articles (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    user_id bigint REFERENCES users(id),
    article_id bigint REFERENCES articles(id),
);



article_to_article_cite oluşturma

CREATE TABLE article_to_article_citations (
    id SERIAL PRIMARY KEY,
    "alinti_yapan" INT NOT NULL,
    "alinti_yapılan" INT NOT NULL,
    FOREIGN KEY ("alinti_yapan") REFERENCES articles(id),
    FOREIGN KEY ("alinti_yapılan") REFERENCES articles(id)
);


tabloyu sıfırdan doldurma 

INSERT INTO article_to_article_citations ("alinti_yapan", "alinti_yapılan")
SELECT a.id AS "alinti_yapan", ac_cited.id AS "alinti_yapılan"
FROM articles a
JOIN articles_citing ac ON a.name = ac.name
JOIN articles ac_cited ON ac.cited_article_id = ac_cited.id;


sadece yenileri ekleme 

INSERT INTO article_to_article_citations ("alinti_yapan", "alinti_yapılan")
SELECT a.id AS "alinti_yapan", ac_cited.id AS "alinti_yapılan"
FROM articles a
JOIN articles_citing ac ON a.name = ac.name
JOIN articles ac_cited ON ac.cited_article_id = ac_cited.id
LEFT JOIN article_to_article_citations atac ON a.id = atac.alinti_yapan AND ac_cited.id = atac.alinti_yapılan
WHERE atac.id IS NULL;


sadece yeniler ama büyük küçük harfe duyarsız

INSERT INTO article_to_article_citations ("alinti_yapan", "alinti_yapılan")
SELECT a.id AS "alinti_yapan", ac_cited.id AS "alinti_yapılan"
FROM articles a
JOIN articles_citing ac ON LOWER(a.name) = LOWER(ac.name)
JOIN articles ac_cited ON ac.cited_article_id = ac_cited.id
LEFT JOIN article_to_article_citations atac ON a.id = atac.alinti_yapan AND ac_cited.id = atac.alinti_yapılan
WHERE atac.id IS NULL;



user_to_user_cite tablosu oluşturma

CREATE TABLE user_to_user_citations (
    id SERIAL PRIMARY KEY,
    "alinti_yapan_user" INT NOT NULL,
    "alinti_yapılan_user" INT NOT NULL,
    "alinti_yapan_article" INT NOT NULL,
    "alinti_yapılan_article" INT NOT NULL,
    FOREIGN KEY ("alinti_yapan_user") REFERENCES users(id),
    FOREIGN KEY ("alinti_yapılan_user") REFERENCES users(id),
    FOREIGN KEY ("alinti_yapan_article") REFERENCES articles(id),
    FOREIGN KEY ("alinti_yapılan_article") REFERENCES articles(id)
);

user_to_user_cite tablosunu doldurma

INSERT INTO user_to_user_citations ("alinti_yapan_user", "alinti_yapılan_user", "alinti_yapan_article", "alinti_yapılan_article")
SELECT DISTINCT ua1.user_id AS "alinti_yapan_user", ua2.user_id AS "alinti_yapılan_user", atac.alinti_yapan AS "alinti_yapan_article", atac.alinti_yapılan AS "alinti_yapılan_article"
FROM article_to_article_citations atac
JOIN user_articles ua1 ON atac.alinti_yapan = ua1.article_id
JOIN user_articles ua2 ON atac.alinti_yapılan = ua2.article_id;

user_to_user_cite tablosunu sadece yenileri ekleme 

INSERT INTO user_to_user_citations ("alinti_yapan_user", "alinti_yapılan_user", "alinti_yapan_article", "alinti_yapılan_article")
SELECT DISTINCT ua1.user_id AS "alinti_yapan_user", ua2.user_id AS "alinti_yapılan_user", atac.alinti_yapan AS "alinti_yapan_article", atac.alinti_yapılan AS "alinti_yapılan_article"
FROM article_to_article_citations atac
JOIN user_articles ua1 ON atac.alinti_yapan = ua1.article_id
JOIN user_articles ua2 ON atac.alinti_yapılan = ua2.article_id
LEFT JOIN user_to_user_citations utuc ON ua1.user_id = utuc.alinti_yapan_user AND ua2.user_id = utuc.alinti_yapılan_user AND atac.alinti_yapan = utuc.alinti_yapan_article AND atac.alinti_yapılan = utuc.alinti_yapılan_article
WHERE utuc.id IS NULL;


kendi kendine alıntı yapan user ve alıntı alinti_sayısı

SELECT alinti_yapan_user, COUNT(*) AS alinti_sayisi
FROM user_to_user_citations
where alinti_yapan_user = alinti_yapılan_user
GROUP BY alinti_yapan_user
ORDER BY alinti_sayisi DESC;