-- Active: 1706448604919@@127.0.0.1@5433@cities
BEGIN;

CREATE TABLE users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    orcid TEXT,
    name VARCHAR(255) NOT NULL,
    google_scholar_code TEXT,
    profile_url TEXT,
    is_found BOOLEAN DEFAULT FALSE,
    is_processed boolean DEFAULT FALSE
);


CREATE TABLE articles (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    user_id bigint REFERENCES users(id),
    tr_tag text,
    name text,
    makale_kod text,
    alinti_kod text,
    alinti_sayisi INTEGER,
    makale_url text,
    alinti_url text,
    is_processed BOOLEAN DEFAULT FALSE
);

CREATE TABLE articles2 (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    tr_tag text,
    name text,
    makale_kod text,
    alinti_kod text,
    alinti_sayisi INTEGER,
    makale_url text,
    alinti_url text,
    is_processed BOOLEAN DEFAULT FALSE,
    is_processed_2 boolean DEFAULT FALSE,
    is_found boolean DEFAULT TRUE
);


COMMIT;


