

CREATE TABLE articles (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    user_id bigint REFERENCES users(id),
    tr_tag text,
    name text,
    makale_kod text,
    alinti_kod text,
    alinti_sayisi INTEGER,
    makale_url text,
    alinti_url text,
    is_processed BOOLEAN DEFAULT FALSE
);

BEGIN;

ALTER TABLE users ADD COLUMN "is_processed" boolean DEFAULT FALSE;

COMMIT;
